# See reveal.js themes here: https://revealjs.com/themes/
# Use "black" for dark mode.
theme: white
# See higlight.js themes here: https://highlightjs.org/static/demo/
# Use "atom-one-dark.min.css" for dark mode. Other reasonnable light themes include xcode.css and vs.css.
header-includes: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/atom-one-light.min.css">'
# Reveal.js options can be set form pandoc: https://github.com/jgm/pandoc/blob/master/data/templates/default.revealjs#L95
width: 1200
height: 675
margin: 0.14
transition: none
history: true
center: false
header-includes: '<link rel="stylesheet" href="custom.css" />'
include-after: '<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/languages/scala.min.js"></script><script>hljs.highlightAll();</script>'
